### PR TITLE
Updated to kordex 1.5.5-SNAPSHOT

### LINKED ISSUE #3: Not compatible with Kordex 1.5.5-SNAPSHOT
I tried to use this in my project but it seems that it is not compatible with the latest snapshot version.

I needed the latest snapshot because I wanted to use `allowInDms = false`.
But during build I am getting the following error:
`Exception in thread "main" java.lang.IncompatibleClassChangeError: class io.github.qbosst.kordex.commands.hybrid.AbstractHybridCommand overrides final method com.kotlindiscord.kord.extensions.commands.Command.getTranslationsProvider()Lcom/kotlindiscord/kord/extensions/i18n/TranslationsProvider;
`

### PR DESCRIPTION
**Pull request by Glennmen**
Fixes #3 

Not sure if what I did was correct 😅

### CODE REVIEW

**Comment by Glennmen** [comment]
@qbosst If you can find the time to look at my PR that would be awesome 😇  my build is currently failing because of the missing `allowInDms`.

**Comment by bosukas** [comment]
Hey,

I think for the allowInDms parameter it should be part of hybrid abstract commands
when it comes to converting it into a slash command, it will override the allowInDms variable in SlashCommand
when it comes to converting it into a message command, if enabled, it should add a check that prevents the message command from being used in DMs

Also, I think it would be also be great if you could add a command that tests this functionality in the test extension, and then use the test extension to make sure everything works

What do you think?
Thanks

**Comment by bosukas** [comment]
Oh, and also update the project version, incase anyone is using this on an older version, so it doesn't break

**Comment by Glennmen** [comment]
@qbosst I did the changes you requested.
CleanShot 2022-09-03 at 16 59 24@2x

**Comment by bosukas** [comment]
I've merged and published your PR, let me know how it goes

Thank you!

**Pull request merged**
